### ISSUE TITLE
EAPP - Last Imported: Time is not correct

### ISSUE THREAD

**Issue by jeandomagni** [jeandomagni/SampleProject#10]
Last Imported Time for Import Voter File on upper left side is following European time zone.

Acceptance Criteria :
Last imported : Time should be same as selected on ePulse settings

**Comment by ershovd** [comment]
@jeandomagni can you please clarify what is wrong with time? Format or value itself? I've changed format to "month\day\year, hour:minute (PM or AM)". if the value itself is wrong - can you make an example which value it is showing vs. what supposed to show.
