### ISSUE TITLE
EAPP - Asus Android 4.2.1 - Sync cloud Icon does not sync and holding for 2 seconds cause app to crash

### ISSUE THREAD

**Issue by jeandomagni** [jeandomagni/SampleProject#7]
Correct the following behavior: Asus Android 4.2.1 Sync cloud icon is not syncing Pressing and holding sync cloud icon on global tool bar (upper right) for 2 seconds cause app to crash

Acceptance Criteria:
Given that a user is logged into an EA Poll Pad
And that they are viewing a module which displays the global tool bar
And that the user presses and holds a sync cloud icon on global tool bar icon for more than 2 seconds, it should not cause app to crash

**Comment by ershovd** [comment]
this is one need more info. could not confirm on generic models. fixed potential crash issue when clicking on sync
